### ISSUE TITLE
Versions are hard-coded

### ISSUE THREAD

**Issue by quobjoern** [quobyte/kubernetes#14]
The Quobyte version is hard coded into the example files, e.g. quobyte-deploy/kubernetes/data-ds.yaml

**Comment by johscheuer** [comment]
Yes, the main problem is that Kubernetes doesn't support such a template mechanism out-of-the box. Some possible solutions for this issue would be:

1.  We replace the version with `QUOBYTE_VERSION` and before running the scripts you have to run `sed` to replace it with the actual value (can also be done in a Makefile)
2. Using helm https://github.com/kubernetes/helm this would force users to install helm in the cluster and on their machine + we would need to create helm charts
3. You can use the deployer written by me https://github.com/inovex/quobyte-kubernetes-operator this is actually only a little bit Python clue code that allows to set the Quobyte version + some additional informations

**Comment by casusbelli** [comment]
Image version tag used ensures that the lates release is loaded, so this should be fine for now.
