### ISSUE TITLE
Only a single registry endpoint is supported

### ISSUE THREAD

**Issue by quobjoern** [quobyte/kubernetes#15]
https://github.com/quobyte/quobyte-deploy/blob/master/kubernetes/client-ds.yaml#L24
does not work when specifying multiple registries.

**Comment by johscheuer** [comment]
Are these registries running out-side of Kubernetes?

The main idea here is that you specify the Quobyte registry service name (from kubernetes) e.q. `registry` and the this step resolves all pod IP's behind the service name/IP. I hope this helped you a little bit further. 

Probably we could improve the documentation there.

**Comment by quobjoern** [comment]
Hi Johannes,

I think it would be helpful if we can also make it work with Quobyte running outside of k8s. Especially when testing people run into the problem that they don't have an SRV record configured. We could check for commas in the QUOBYTE_REGISTRY parameter and not do the address resolution if it contains commas?

**Comment by casusbelli** [comment]
This has been FIXED not closed, i used the wrong Github tag (sry for that).
